### ISSUE TITLE
Bug:  Upgrade fail to migrate SPU

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1338]
Steps to produce reproduce it:

1) Install latest stable
2) Perform update using: 
```
flvd cluster upgrade --sys
flvd cluster upgrade --develop
```

Note that helm show everything is upgraded:
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART               APP VERSION
fluvio          default         2               2021-07-29 23:33:35.31239047 +0000 UTC  deployed        fluvio-app-0.9.0    0.9.0      
fluvio-sys      default         2               2021-07-29 23:33:22.191279718 +0000 UTC deployed        fluvio-sys-0.9.0    0.9.0   
```

but SPU still show it is running old version:
```
    env:
    - name: SPU_INDEX
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: SPU_MIN
      value: "0"
    - name: RUST_LOG
      value: info
    image: infinyon/fluvio:0.8.5
    imagePullPolicy: IfNotPresent
    name: spu
    ports:
    - containerPort: 9005
      name: public
      protocol: TCP
    - containerPort: 9006
```

But SC shows it is upgraded:
```
  containers:
  - command:
    - /fluvio-run
    - sc
    env:
    - name: RUST_LOG
      value: info
    image: infinyon/fluvio:18f5578d85a679c7b63b53bdcef6c42f5267638c
    imagePullPolicy: IfNotPresent
    name: fluvio-sc
    ports:
```
