### ISSUE TITLE
Platform: Mac K8 installation is not working Docker

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1363]
Relevant link: https://github.com/kubernetes/minikube/issues/11193.

Docker does not provide way for host access container port directly.

**Comment by sehz** [comment]
This is not verified to working with Docker.   This have to be done with cluster installer reworking

**Comment by sehz** [comment]
closing this for now unless someone requested support for Docker for Mac

**Comment by sehz** [comment]
Hyperkit driver works for minikube here:  https://www.fluvio.io/docs/get-started/mac/.  closing it

**Comment by sehz** [comment]
hyperkit doesn't work on M1 so need another workaround

**Comment by sehz** [comment]
Latest K3d removed ` --no-hostip -` option so need solution quickly

**Comment by sehz** [comment]
relevant issue: https://github.com/kubernetes/minikube/issues/11193

**Comment by sehz** [comment]
Key issue is that Docker doesn't forward ports from minikube containers.   This can be work around in the [kind](https://kind.sigs.k8s.io/docs/user/configuration#extra-port-mappings) by creating using this config:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30007
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    listenAddress: "127.0.0.1"
    # optional: set the protocol to one of TCP, UDP, SCTP.
    # TCP is the default
    protocol: TCP
```
Assuming fluvio adds node port mapping for public services
````
apiVersion: v1
kind: Service
metadata:
  name: fluvio-sc-public
  annotations:
    {{- toYaml .Values.loadBalancer.serviceAnnotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fluvio-sc
{{ if .Values.service.externalTrafficPolicy }}
    externalTrafficPolicy: .Values.service.externalTrafficPolicy
{{ end }}
{{ if .Values.service.externalName }}
    externalName: .Values.service.externalName
{{ end }}
  ports:
  - protocol: TCP
    port: 9003
    targetPort: 9003
    nodePort: 30007
````

The minikube command for port forwarding doesn't work on current version and it is not customizable as kind:
```
minikube start --driver=docker --extra-config=apiserver.service-node-port-range=32760-32767 --ports=127.0.0.1:32760-32767:32760-32767
```
