### ISSUE TITLE
Use Internal Address for Fluvio Config inside a Managed Connector

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#1537]
When running a fluvio client outside k8, the config has an endpoints per profile.
For example, a local k8 cluster has:

```toml
[cluster."127.0.0.1"]
endpoint = "192.168.49.2:9003"

[cluster."127.0.0.1".tls]
tls_policy = "verified"
tls_source = "inline"
```

A given connector will run inside the k8s cluster so the endpoint will not be the same. This needs to also be solved in the spu return.

https://github.com/infinyon/fluvio-connectors/issues/13 is the old ticket for this.

After a discussion, it seems that the most ideal user experience to have a field on [`FluvioConfig`](https://github.com/infinyon/fluvio/blob/927ccf4ce316f89e7f5e25014aa0cc7992f4006a/crates/fluvio/src/config/cluster.rs#L13-L24), to use "internal endpoints" (name undecided). This should be used in [`connect_to_leader` in spu.rs](https://github.com/infinyon/fluvio/blob/927ccf4ce316f89e7f5e25014aa0cc7992f4006a/crates/fluvio/src/spu.rs#L76-L91).
