### ISSUE TITLE
Add CLI commands for managing Table definitions

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#1759]
```
fluvio tables create <name> --config-file=path/to/yaml 
fluvio tables delete <name> 
fluvio tables list
```

Table Config Schema
```
format: json|yaml|toml
columns:
- <column_id>:
    label: <display>
    width: <max num of characters>
    alignment: left|center|right
    path: <path to field in well-defined format>
    format: date|datetime
smartmodules:
  format: <name of smart module>
```

Table Config Example
```yaml
format: json
columns:
- busId:
    label: Bus ID
    width: 25
    alignment: left
    path: .busId (optional)
    format: datetime
smartmodules:
  format: my-table-formatter
```

Consume
```
fluvio consume mytopic --table=bus_table --columns=busId,arrivalTime 
```
