### ISSUE TITLE
[Bug]: Fluvio Cluster failed to install on microk8s

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1933]
**What happened**
Try to install fluvio on [microk8s](https://microk8s.io)

**Expected behavior**
Installation

**Describe the setup**
```
$ fluvio version
Fluvio CLI           : 0.9.13
Fluvio CLI SHA256    : 2f41e2874c1390657c2574fcd53ff4c9a4f12a7b463be2a4e8efc5afa55870c0
Fluvio Platform      : Not available (kind-kind)
Git Commit           : e1ef6333f3fb12660a096f2ad697961ab2b085db
OS Details           : Darwin 10.16 (kernel 21.1.0)
=== Plugin Versions ===
Fluvio Runner (fluvio-run)     : 0.0.0
Infinyon Cloud CLI (fluvio-cloud) : 0.1.6
```

**How to reproduce it (as minimally and precisely as possible)**
```
 fluvio cluster start
Error: 
   0: Fluvio cluster error
   1: Failed to install Fluvio on Kubernetes
   2: Kubernetes client error
   3: no client cert crt path founded
   4: no client cert crt path founded
```

**Environment (please complete the following information):**
 - OS: [Mac]
 - Fluvio Version [e.g. 22]

**Comment by sehz** [comment]
This is Kubernetes config:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVWTc3L0VDNHYweDI2K2VOMEJSMUxwUFgzQjd3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXhNVEV5TURJd016a3lObG9YRFRNeApNVEV4T0RJd016a3lObG93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4b0Q5NDNVTGlDdWdYUm5ueDdFMndFTkRPVkduYTA2VktkaUsKY1drNXhJRCtWeVhnV1pWcTN2U3N6S2xxemUrcnQ0bjYzVmZSeWpycmprM3NvMFNNRy9lZEdDajlnY0w2RjZTdgpGYURwY2lwdDhBYTRKVHFJbUY0U0w1UzJKb0RoUjJNdnFWKzRZd2N1d21zZXA5aE14ZGtSRnIzZTNyU0lvR0ltClVudEtRYkRCVmZNVlFiSXBibDFVenAyU3FnZ0xQMHdMbTdBcXdzVVVLUzBEV2puUUNxbmpUb3RyVUp5bHRhRXcKM2VWc3FVeXJCdUNIRHhESW1KOGtDdERwWG1YQlJSZXQ2bkZ6SGJmSHB3MHFPd3hCS3ZrTkRnc1EvdVJudWZVawpYM1QzZVlXak5wb3VlREhaQm9vV2FhZ2hhWGZLajdxcWg0VDlRbWJGcXYzcHErMWxwd0lEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVXFGd2tDcGZWOHFkUW9qTHIxbXJOaDdLWUJkd3dId1lEVlIwakJCZ3dGb0FVcUZ3a0NwZlYKOHFkUW9qTHIxbXJOaDdLWUJkd3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBRGhoU29VUlZQdWRrZFdkSk5rbVNDcGlOWFp3OFV5b09ZVjNrenpzY1JCemZKRUJUVnorWDhOY2NyUTFsCmx1RFJXVTdiSEJlejcwM1hJVEVUbHo3VmhyZE04Z3hZWEhuNng2dTVvZDJMVlhmbUZ5bVpMWVNRQ1kxeXNtOXgKZlhURjdRcGhFc1BwclU4ZVVERTlvaUNzR29hS0IrR0lIRDgzM3hEWkNTd0d0dHlPOXpTUmE4UDNhNm5YRGR0YwpnR090Mm5kVDFLaTRFUlJyZW82cU4yb0h0WlRyL0dWcVlrNE9IY1pWK1dzZEJOM0xLSjFja1VoK2NNWU9MdWJzCm5qeUwvV1g3U3QyL3dTWmt0RzUyZ2JueHpMYmtCR3ZCSE01UVIzQlIvWnF2Z0Yyai9oNmtVUnp0Lyt1a3l4NjEKWWFPb1V4QWJIV1J0WlpvR3NTZTNmcjJ3bmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.64.4:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: QVRvZXhjRVU0QjIrZXJnMHBwTEZnZk56RnNMc3dWUkdmTXJITXM5cklCQT0K

```
