### ISSUE TITLE
Workflow artifacts should have short retention

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#2139]
Retention can be set on the `upload-artifact` action.

Example
```
  - name: Upload Artifact
    uses: actions/upload-artifact@v2
    with:
      name: my-artifact
      path: my_file.txt
      retention-days: 5
```
