### ISSUE TITLE
Upgrade CLI to use Clap v3 over StructOpt

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#2166]
Looks like all the functionality of [`StructOpt` has been added to Clap](https://github.com/TeXitoi/structopt#maintenance):

> As clap v3 is now out, and the structopt features are integrated into (almost as-is), structopt is now in maintenance mode: no new feature will be added.
> 
> Bugs will be fixed, and documentation improvements will be accepted.

Doesn't look too hard: https://github.com/clap-rs/clap#example

**Comment by sehz** [comment]
@thehabbos007 reopening issue due to failure in CD test

**Comment by thehabbos007** [comment]
Hey, I added some diagnostics to check how the pods looked, and this is what I got on my fork
https://github.com/thehabbos007/fluvio/runs/5833442204?check_suite_focus=true#step:4:286
Did i forget to bump a version somewhere in order to get an appropriate image?

**Comment by sehz** [comment]
Seems like some of CI runs against dev are failing.  Could be due to GH instability.

**Comment by sehz** [comment]
With this change, `latest` release is failing to install.
```
containerStatuses:
  - image: infinyon/fluvio:0.9.23
    imageID: ""
    lastState: {}
    name: fluvio-sc
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "infinyon/fluvio:0.9.23"
        reason: ImagePullBackOff
  hostIP: 192.168.50.106
```

This happens probably because fluvio channel needs to be updated.
