### ISSUE TITLE
Allow keys and dictionaries to parameters section of connector yaml

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#2410]
This is a subtask of https://github.com/infinyon/fluvio-connectors/issues/260

Our connectors yaml should support values and dictionaries in the `parameters` section. Example:
```yaml
version: dev
name: kafka-output
type: kafka-source
topic: fluvio-output
create_topic: true
parameters:
  kafka-topic: fluvio
  kafka-url: "192.168.1.12:9092"
  header:
    - "foo: bar"
    - "bar: baz"
```

In this example, the SC controller will `headers` dictionary will add duplicate commandline arguments to the connector at https://github.com/infinyon/fluvio/blob/32433325185edab66b8bffed46af0f7730887af9/crates/fluvio-sc/src/k8/controllers/managed_connector_deployment.rs#L224-L229
