### ISSUE TITLE
Expose producer options in connector config

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#2421]
Intent is to expose options that affect the performance of a connector

For example:
```yaml
version: 0.2.0
name: source-connector-draft
type: http
topic: cat-facts
direction: source
producer:
  linger: 1ms
  batch_size: 44
  compression: gzip
parameters:
  endpoint: https://catfact.ninja/fact
  interval: 10
  map: "catfact-map"
```
