### ISSUE TITLE
Add `connector describe` command

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#2458]
Users need the ability to see what are the connector parameters used to provision the connectors.

```
fluvio connector describe github-stars-input
name: github-stars-input
type: http
topic: github-stars
create_topic: true
direction: source
parameters:
  endpoint: 'https://api.github.com/repos/infinyon/fluvio'
  method: GET
  interval: 30
  header: 'Authorization: token ****'
  aggregate: star-selector
  aggregate-initial-value: "use-last"
```
