### ISSUE TITLE
Move SmartModule configuration in connectors to top level configuration in Connectors config:

### ISSUE THREAD

**Issue by morenol** [infinyon/fluvio#2471]
We should configure smart modules in their own section `smartmodule` of the connectors config.
```yaml
...
smartmodule: # optional
  name: string # required
  type: string # (valid values: filter, map, filter_map, aggregate, array_map) -> Optional once we have: https://github.com/infinyon/fluvio/issues/2457
  aggregate_initial_value: 1 # optional
  parameters: # optional
    key: value
    foo: bar
...
```
