### ISSUE TITLE
CLI: import CSV file 

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2989]
```
$ fluvio producer --csv <csv_file>
```

This would producer files int the CSV format

**Comment by biryukovmaxim** [comment]
I think about take this issue to implement. @sehz , could you clarify requirements? Should it support binary records containing non-valid utf-8? What about header record? Should it be handled by special cli flags? additional parameter for delimiter to support something like tsv too?

**Comment by ajhunyady** [comment]
This issue was filled before https://github.com/infinyon/fluvio/issues/2988 committed by @crajcan. This this issue addressed, we should implement the `csv` transformation in a smartmodule.

The benefits of this approach is that the transformations can also be used in connectors and consumers.
So, I suggest implementing something similar to: https://github.com/infinyon/labs-rss-json-sm

Then we can produce csv as follows:

```
fluvio produce --smartmodule infinyon/csv-json@0.1.0
```

and we can also use as part of a connector:

```
apiVersion: 0.1.0
meta:
  version: 0.1.0
  name: csv-transform
  type: http-source
  topic: csv-transform
http:
  endpoint: "https://example.com/csv-endpoint"
  interval: 10s
transforms:
  - uses: infinyon/csv-json@0.1.0
```
