### ISSUE TITLE
[Bug]: CDK config validation with mutually exclusive secrets

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#3087]
**What happened**
Following instructions from the MQTT readme at https://github.com/infinyon/mqtt-connector, I was unable to start a connector with the example due to config validation.

**Expected behavior**
The `url` option is supposed to be mutually exclusive with a definition included as a secret, but instead is required 

**Describe the setup**
```
% fluvio install cdk
Current channel: latest
🎣 Fetching latest version for package: fluvio/cdk...
⏳ Downloading package with latest version: fluvio/cdk:0.10.6-dev-1+220cb47bf60e45600c946b133c5f2350117b034d...
🔑 Downloaded and verified package file
```

**How to reproduce it (as minimally and precisely as possible)**
```shell
fluvio hub connector download infinyon/mqtt-source@0.1.2 --remote https://hub-dev.infinyon.cloud/
```

```yaml
# config-example.yaml
meta:
  version: latest
  name: my-mqtt-connector
  type: mqtt-source
  topic: mqtt-topic
  create-topic: true
mqtt:
  url: "mqtt://test.mosquitto.org/"
  topic: "mqtt-to-fluvio"
  client_id: "my_mqtt"
  timeout:
    secs: 30
    nanos: 0
  payload_output_type: json
```

```
cdk deploy start --ipkg infinyon-mqtt-source-0.1.2.ipkg --config config-example.yaml
```

**Log output**
```
cdk deploy start --ipkg infinyon-mqtt-source-0.1.2.ipkg --config config-example.yaml
... checking package
Error: missing required secret 'MQTT_URL' in config
```
