### ISSUE TITLE
CDK: Ensure binaries and readme are included in tarball

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/fluvio#3197]
When generating the `package-meta.yml` using `cdk publish --pack -p <PACKAGE NAME>`
the only file path appended to the `manifest` is `Connector.toml`, the binary itself and the
README are not being added to the list of files under `manifest` key.

```yaml
package_format_version: '0.3'
name: http-sink
version: 0.1.0
group: infinyon
description: HTTP sink connector reads records from data streaming and generates an HTTP request
license: e.g. Apache2
visibility: public
manifest:
  - ../Connector.toml
tags: null
```

This causes the following error to occur when attempting to run `cdk deploy` and when publishing packages.

```log
Error: Failed to deploy from ipkg file
Caused by:
     Package missing http-sink file
```

> Here is the fragment of code where the error is generated
>
> https://github.com/infinyon/fluvio/blob/4cabea8aa9d5acebc687c108c35297da327adb47/crates/cdk/src/deploy.rs#L204-L210

The expected output should be:

```diff
package_format_version: '0.3'
name: http-sink
version: 0.1.0
group: infinyon
description: HTTP sink connector reads records from data streaming and generates an HTTP request
license: e.g. Apache2
visibility: public
manifest:
   - ../Connector.toml
+   - ../../../target/release/http-sink
+   - ../../../README.md
tags: null
```
