### ISSUE TITLE
Support time bound in lookback engine

### ISSUE THREAD

**Issue by galibey** [infinyon/fluvio#3357]
We need to support the lookback engine querying existing records by "age" - read records that are not older than the given age parameter:
```yaml
transforms:
  - uses: infinyon/bloom-filter@0.1.0
    with:
      lookback:
        age: 2d
```
