### ISSUE TITLE
[Bug]: `cdk deploy` with multiple connectors can fail with log file name collisions

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3903]
**What happened**

```
$ cdk deploy start --ipkg infinyon-http-source-0.3.3.ipkg -c c1-connector.yaml
$ cdk deploy start --ipkg infinyon-http-source-0.3.3.ipkg -c c2-connector.yaml
```
Results in one stopped connector if both deploys are run in the same directory

```
cdk deploy list
 NAME    STATUS
 c1           Running
 c2           Stopped
```

**Expected behavior**

Both connectors should run
```
cdk deploy list
 NAME    STATUS
 c1           Running
 c2           Running
```

**Describe the setup**
Using connectors downloaded for locally running them.
`cdk hub download infinyon/http-source@0.3.3`

Create two configs with a different name:
``
apiVersion: 0.2.0
meta:
  version: 0.3.2
  name: c1
  type: http-source
  topic:
    version: 0.1.0
    meta:
      name: sentence 
http:
  endpoint: https://demo-data.infinyon.com/api/quote-stream
  method: GET
  stream: true
  delimiter: "\n\n"
  ```
  ``
apiVersion: 0.2.0
meta:
  version: 0.3.2
  name: c2
  type: http-source
  topic:
    version: 0.1.0
    meta:
      name: sentence 
http:
  endpoint: https://demo-data.infinyon.com/api/quote-stream
  method: GET
  stream: true
  delimiter: "\n\n"
  ```
  

**How to reproduce it (as minimally and precisely as possible)**
```
$ cdk hub download infinyon/http-source@0.3.3`
$ cdk deploy start --ipkg infinyon-http-source-0.3.3.ipkg -c c1-connector.yaml
$ cdk deploy start --ipkg infinyon-http-source-0.3.3.ipkg -c c2-connector.yaml
$ cdk deploy list
```
