### ISSUE TITLE
Add: ability for fluvio connectors to perform record.json.property template parsing and rendering

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3920]
Allow for e.g. query parameter additions onto

```
# config-example-params.yaml
apiVersion: 0.1.0
meta:
  version: 0.2.5
  name: my-http-sink
  type: http-sink
  topic: http-sink-topic
  secrets:
    - name: AUTHORIZATION_TOKEN
http:
  endpoint: "https://someurl.com${{ record.json.uri_param }}"
  headers:
    - "Authorization: token ${{ secrets.AUTHORIZATION_TOKEN }}"
    - "Content-Type: application/json"
```

A json record with a  "uri_param" can come from the topic, or have parameters added via smartmodule. 

From 3/28/2024 10am PST discussion
