### ISSUE TITLE
Bug: Connector ignore invalid transformation configuration

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#4003]
Steps to reproduce.  If any transforms section contains invalid configuration like:
```
# config-example.yaml
apiVersion: 0.1.0
meta:
  version: 0.3.3
  name: cat-facts
  type: http-source
  topic: cat-facts
  create-topic: true
http:
  endpoint: "https://catfact.ninja/fact"
  interval: 10s
transforms:
  - uses: infinyon/jolt@0.1.0
    with:
      -   spec:
             - operation: default
               spec:
                source: "http-connector"
             - operation: remove
                spec:
                 length: ""
```

connector silently drops transform section which cause user to think transform is not working when in fact transform is not even applied.
