### ISSUE TITLE
support humantime_serde in flush-period field

### ISSUE THREAD

**Issue by fraidev** [infinyon/fluvio#4274]
It would be nice `flush-period` field of consumer offset config **also** support `humantime_serde`.

now:

```
apiVersion: 0.2.0
meta:
  consumer:
    partition: all
    id: $CONNECTOR_NAME
    offset:
      strategy: auto
      start: beginning
      flush-period:
        secs: 10
        nanos: 0
```

expected:
```
apiVersion: 0.2.0
meta:
  consumer:
    partition: all
    id: $CONNECTOR_NAME
    offset:
      strategy: auto
      start: beginning
      flush-period: 10s
```
