### ISSUE TITLE
Deduplication does not work if `count` is omitted. Should error instead.

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#4282]
**What happened**
When omitting `count:` from topic deduplication crd, the setup can prevent client connector to the topic.

**Expected behavior**
Rejection of the misconfigured field or an error log which points to the missing 'count' value if deduplication is enabled

**Describe the setup**
A user on discord [1](https://discord.com/channels/695712741381636168/1313345931751723078/1313346039994126336)  was able to setup a topic with two configs, one of which (missing `count`, was failing to connect.

Working config
```yaml
# topic.yaml
version: 0.1.0
meta:
  name: grpc-txs
deduplication:
  bounds:
    count: 5 # remember at least 5 last records
    age: 5s # remember records for at least 5 seconds
  filter:
    transform:
      uses: infinyon-labs/dedup-filter@0.0.2
```

Failing config. Note the missing 'count' field under deduplication.

```yaml
apiVersion: fluvio.infinyon.com/v2
kind: Topic
metadata:
  name: grpc-txs
  namespace: fluvio
spec:
  cleanupPolicy:
    segment:
      timeInSeconds: 86400
  replicas:
    computed:
      partitions: 3
      replicationFactor: 2
  deduplication:
    bounds:
      age: 5s
    filter:
      transform:
        uses: infinyon-labs/dedup-filter@0.0.2
```
