### ISSUE TITLE
Connector: Expand support for topic configuration

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#4342]
# Introduction
 Current connector only allow name of the topic.  This doesn't allow user to specify additional parameter for customization.  The topic configuration should allow for all parameters in the topic.

## Topic metadata

So instead of currently:
```
apiVersion: 0.1.0

meta:
 name:  my-config
 version: 0.1.0
 type: http-source
 topic:  quotes
```

We should have something like this:
```
apiVersion: 0.2.0
meta:
 name:  my-config
 version: 0.1.0
 type: http-source
 topic:  
      name: quotes
      managed:
         partitions: 10
         replication: 3
```

` managed` is connector managed configuration.  Topic is either created externally or managed by connector.  if topic is managed by connector but is configured externally, connector would error out instead of starting.

It should expose all topic parameter such as:

- replica-assignment
- mirror-apply
- retention-time
- segment-size
- compression-type
- max-partition-type
