### ISSUE TITLE
feature: set SPU and SC addresses on cluster start

### ISSUE THREAD

**Issue by fraidev** [infinyon/fluvio#4490]
Would be good a parameter to set SPU and SC addresses on `fluvio cluster start` 

Maybe diretly passing the private and public server ordered via CLI:
```
fluvio cluster start --spu 3 \
--sc-public-server localhost:9003 --sc-private-server localhost:9004  \
--spu-public-server  "localhost:9010, localhost:9020, localhost:9030" \
--spu-private-server "localhost:9011, localhost:9021, localhost:9031"
```

Or maybe via config a new config file:

```yaml
sc:
  public-server: localhost:9003
  private-server: localhost:9004
spus:
  5001: 
    public-server: localhost:9010
    private-server: localhost:9011
  5002: 
    public-server: localhost:9020
    private-server: localhost:9021
  5003: 
    public-server: localhost:9030
    private-server: localhost:9031
```

- `fluvio cluster start --start-config start-config.yaml`

**Comment by sehz** [comment]
`start-config.yaml`   -> `cluster.yaml`.

Cluster config is required in order to have resume or restart to work.  

The configuration can be specified ( `--cluster-config`)   or created from parameters.    If location of configuration is not specified, it can be stored in the `~/fluvio`.    If not specified directory can be used `--config-path` which implies `cluster.yaml` should be found int he directory.


The configuration can specify:
- Path of the data directory (if not specified, derived from config directory)
- Path of the log directory (if not specified, derived from log directory).
- SC configuration
- List of SPUS with parameters (port, data dir, etc).

The configuration should be extended to profile so user doesn't have to specify again.



# Using YAML configuration.   

```
$ fluvio cluster start --cluster-config /my/cluster1/cluster.yaml
```

The cluster config looks like this:
```
apiVersion:  0.1.0
metadata:
      name:  local2          # this is also name of the profile by default
      type:  local              # valid:  local/k8 for now
sc:   # all fields are optional
     port:
         public:  "localhost:9003"                # optional
         private:  "localhost:9004"                # optional 
    tls:                                                         
        server-cert:  <path> 
        server-key:  <path>
        ca-cert: <path>
spus:
     base:                   # this is common configuration for all SPU, it is optional
            id:       <positive_integer>.   # if specified, base SPU number
            data-dir:  <path>     # if this is specified, spu data are stored under neath by spu id
            data-size: <size>     # amount of data  can be stored in individual SPU
            index-max-bytes: <bytes>
           index-max-interval-bytes: <bytes>
          peer-max-bytes: <bytes>
           smart-engine-max-memory: <bytes>
          port:
                 public:  "localhost:9005"
                 private: "localhost:9006"
    tls:
          server-cert: <path>
          server-key: <path>
          ca-cert: <path>
    config:                 # each individual spu configuration can be overriden from base
          5001:  
                port:
                     public: "localhost:9020"
                     private: "localhost: 9021"         # optional, by default it is increased by 1
```

Then can be stopped and restarted individually (as long port doesn't interfere)

```
$ fluvio cluster stop --cluster-config /my/cluster1/cluster.yaml
``` 

And resumed

```
$ fluvio cluster restart --cluster-config /my/cluster1/cluster.yaml
```
