### ISSUE TITLE
Use `nodePort` rather than `tunnel` for accessing services in the minikube

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#668]
We use [minikube tunnel](https://minikube.sigs.k8s.io/docs/handbook/accessing/) for exposing SC/SPU services to outside cluster.  It however has unfortunately downside that it's difficult to setup and maintain due to different ways to set up depends on OS.  

Alternative is to use `nodeport` which minikube supports.   It also has benefit of being more portable to other K8 setup such as [kind](https://kind.sigs.k8s.io) or [k3](https://rancher.com/products/k3s/).  

This issue is about experimentation to see if it is possible to migrate to `nodeport`

**Comment by sehz** [comment]
this worked: 
```
apiVersion: v1
kind: Service
metadata:
  name: fluvio-sc-public
spec:
  type: NodePort
  selector:
    app: fluvio-sc
  ports:
  - protocol: TCP
    port: 9003
```

But need to way to get public IP address of the minikube which can be done by iterating nodes
